apiVersion: 1

datasources:
  # Elasticsearch datasource
  - name: TaskFlow Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: taskflow-logs-*
    basicAuth: false
    isDefault: true
    jsonData:
      interval: Daily
      timeField: '@timestamp'
      esVersion: '8.0.0'
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5
    readOnly: false

  # PostgreSQL datasource
  - name: TaskFlow Database
    type: postgres
    access: proxy
    url: postgres:5432
    database: taskflow
    user: taskflow
    secureJsonData:
      password: taskflow_password
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    readOnly: false

  # Prometheus-style metrics (if available)
  - name: TaskFlow Metrics
    type: prometheus
    access: proxy
    url: http://taskflow-app:8080
    isDefault: false
    jsonData:
      httpMethod: GET
      timeInterval: 30s
    readOnly: false 